version: '3.2'
services:
  mysql:
    container_name: mysqldocker-mysql-1
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=234non@dfaA
      - TZ=Asia/Bangkok
    volumes:
      - ./mymqli:/var/lib/mysql    
    # command: ['mysqld','--default-time-zone=+07:00']  
networks:
  default:
    name: test